apiVersion: v1
data:
  # Console | base64
  CONSOLE_ACCESS_KEY: Y29uc29sZQ==
  # Console123 | base64
  CONSOLE_SECRET_KEY: Y29uc29sZTEyMw==
kind: Secret
metadata:
  name: storage-user
  namespace: default
type: Opaque