# Deprecated but doesn't seem to work without, at the moment
apiVersion: v1
data:
  accessKey: ""
  secretKey: ""
kind: Secret
metadata:
  name: storage-creds-secret
  namespace: minio-tenant
type: Opaque